################################# Default configuration ###################
baseURL = "https://farfetch-chat.github.io/"
title = "FARFETCH Chat | MultiModal Conversational Agents"
theme = "airspace"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

categories = ["Research"]
project_url = "https://farfetch-chat.github.io/"
# series = ["Go Web Dev"]
slug = "Farfetch Chat R&D"
tags = ["Conversational AI", "Conversational Agents", "natural language processing", "computer vision", "machine learning"]

#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################

[[menu.main]]
name = "Project"
URL = "project"
weight = 2

##################################################################

[[menu.main]]
parent="Project"
name = "Project Portfolio"
URL = "project"

[[menu.main]]
parent="Project"
name = "Overview"
URL = "overview"

[[menu.main]]
parent="Project"
name = "Use Cases"
URL = "usecases"

[[menu.main]]
parent="Project"
name = "Vision"
URL = "about"

[[menu.main]]
parent="Project"
name = "Team"
URL = "team"

##################################################################

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Activities"
URL = "activities"
weight = 4

[[menu.main]]
name = "Opportunities"
URL = "opportunities"
weight = 5

##################################################################
[[menu.main]]
weight = 6
name = "Pages"
hasChildren = true

[[menu.main]]
 parent = "Pages"
 name = "FAQ"
 URL = "faq"

##################################################################
[[menu.main]]
 weight = 7
 name = "Downloads"
 hasChildren = true

[[menu.main]]
 parent = "Downloads"
 name = "DATA"
 URL = "data"

[[menu.main]]
 parent = "Downloads"
 name = "PAPERS"
 URL = "papers"

[[menu.main]]
 parent = "Downloads"
 name = "SOFTWARE"
 URL = "software"

##################################################################
[[menu.main]]
name = "PARTNERS"
URL = "contact"
weight = 3

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "FARFETCH Chat | FARFETCH Chat is a multimodal conversational agents for the online fashion marketplace. Co-promotion initiative with CMU, UNL and IST."
author = "FARFETCH"
# Contact Information
mobile = ""
email = "ifetch@farfetch.com"
location = "Portugal"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-162948195-1" # Your ID
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# # google map
# [params.gmap]
# enable = true
# gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# map_latitude = "51.5223477"
# map_longitude = "-0.1622023"
# map_marker = "images/marker.png"


############################# social site ########################
# [[params.social]]
# icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"
#
# [[params.social]]
# icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"
#
# [[params.social]]
# icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"
#
# [[params.social]]
# icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"
#
# [[params.social]]
# icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"
#
# [[params.social]]
# icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"



################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
image = "images/sponsor/sponsor.png"
# copyright
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ''
    footnoteReturnLinkContents = ''
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2